preset: recommended

linting: true

enabled:
  - long_array_syntax
  - strict
  - unalign_double_arrow

disabled:
  - align_double_arrow
  - short_array_syntax

finder:
  exclude:
    - "tests"
    - "vendor"
    - "composer.json"
    - "composer.lock"
    - "phpunit.xml"
    - "README.md"
  name:
    - "*.php"